title: darrell.thoughts
description: A public journal of ideas, logs, and explorations
name: Darrell Suggs
email: your-email@example.com
url: "https://darrellsuggs.github.io"
baseurl: "/darrell.thoughts"

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge
minimal_mistakes_skin: default

author:
  name: "Darrell Suggs"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Engineer, reader, thinker."

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

nav:
  - title: "thinking-with-experience"
    url: /categories/thinking-with-experience/
  - title: "book-thoughts"
    url: /categories/book-thoughts/
  - title: "thinking-with-ai"
    url: /categories/thinking-with-ai/
  - title: "dad-life"
    url: /categories/dad-life/
